### PR TITLE
Fix binary_extended_gcd

### LINKED ISSUE #96: Bug of `binary_extended_gcd`
I am reading <https://github.com/lemire/Code-used-on-Daniel-Lemire-s-blog/blob/master/2024/04/13/module/gcd.h> and found that `binary_extended_gcd` returns wrong result when giving `a=212, b=31`. Correct result is `g=1, x=6, y=-41`, but `binary_extended_gcd` returns `g=1, x=22, y=-157`, `a*x+b*y=-203` not `1`.

### PR DESCRIPTION
**Pull request by Tiphereth-A**
close #96

Tested in <https://judge.u-aizu.ac.jp/onlinejudge/review.jsp?rid=9101937#2>.

I do not benchmark new codes because I do not have the same environment.

### CODE REVIEW

**Comment by Tiphereth-A** [comment]
I think the main issue is the implicit conversion between signed and unsigned integral...

**Comment by lemire** [comment]
Looks good. Merging. Thanks.

**Comment by lemire** [comment]
Ooops. No, the code is not correct it ends up in an infinite loop.

**Comment by Tiphereth-A** [comment]
> Ooops. No, the code is not correct it ends up in an infinite loop.

Oh, sorry, I forgot the case when `b == 0`.

**Pull request merged**
