### PR TITLE
Fix corner cases of binary_extended_gcd

### PR DESCRIPTION
**Pull request by Tiphereth-A**
fix <https://github.com/lemire/Code-used-on-Daniel-Lemire-s-blog/pull/97#issuecomment-2056936031>

### CODE REVIEW

**Comment by Tiphereth-A** [comment]
> Nope. It still won't work.

Can you give me some sample data?

**Comment by lemire** [comment]
Please pull the latest commit where I reverted the changes and added more tests in the benchmark program. Run the "benchmark" program. It will run tests on all inputs.

**Comment by Tiphereth-A** [comment]
> Please pull the latest commit where I reverted the changes and added more tests in the benchmark program. Run the "benchmark" program. It will run tests on all inputs.

It seems that signed overflow occurred because `max(x, y) > 0x1FFFFFFFFFFFFFFF`...

**Comment by Tiphereth-A** [comment]
It works well in my machine if

```diff
diff --git a/2024/04/13/benchmarks/benchmark.cpp b/2024/04/13/benchmarks/benchmark.cpp
index 6df7763..c4b4462 100644
--- a/2024/04/13/benchmarks/benchmark.cpp
+++ b/2024/04/13/benchmarks/benchmark.cpp
@@ -37,7 +37,7 @@ int main(int argc, char **argv) {
   const size_t N = 2048;
   std::random_device rd;
   std::mt19937_64 gen(rd());
-  std::uniform_int_distribution<uint64_t> dis;
+  std::uniform_int_distribution<uint64_t> dis(0, std::numeric_limits<uint64_t>::max() / 8);
 
   std::vector<uint64_t> vector1;
   std::vector<uint64_t> vector2;
```

**Comment by lemire** [comment]
It no longer enters an infinite loop if I apply this change on your PR, but I get...

```
# binary_extended_gcd is incorrect
#   x: 2248014058122851555, y: 523771174175409721
#   bezout.x: 41330250634979795, bezout.y: 18269342023708491048, gcd: 1
```

So the result is still not correct.

**Comment by Tiphereth-A** [comment]
> It no longer enters an infinite loop if I apply this change on your PR, but I get...
> 
> ```
> # binary_extended_gcd is incorrect
> #   x: 2248014058122851555, y: 523771174175409721
> #   bezout.x: 41330250634979795, bezout.y: 18269342023708491048, gcd: 1
> ```
> 
> So the result is still not correct.

Oh, I see, I forgot <https://github.com/Tiphereth-A/Code-used-on-Daniel-Lemire-s-blog/blob/aa6b950a8439a4deb850b183f4c174fd76badb78/2024/04/13/module/gcd.h#L105-L106> and <https://github.com/Tiphereth-A/Code-used-on-Daniel-Lemire-s-blog/blob/aa6b950a8439a4deb850b183f4c174fd76badb78/2024/04/13/module/gcd.h#L115-L116>, it would be work if using `std::midpoint`.

**Comment by lemire** [comment]
> it would be work if using std::midpoint.

It does not seem to work in my tests. :-(

**Comment by Tiphereth-A** [comment]
> > it would be work if using std::midpoint.
> 
> It does not seem to work in my tests. :-(

I have run 128 times of benchmarks on my machine and it works well, I will open another PR to show that.

**Comment by Tiphereth-A** [comment]
> > it would be work if using std::midpoint.
> 
> It does not seem to work in my tests. :-(

Sorry I meet another issue now, I would be think a new way to solve that...

**Pull request merged**
